{% set name = "gwf" %}
{% set version = "2.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m flit install --deps none"

requirements:
  host:
    - flit
    - attrs
    - click
    - click-plugins
    - python>=3.7
    - importlib_metadata>=4.6 # [py37]
  run:
    - attrs
    - click
    - click-plugins
    - python>=3.7
    - importlib_metadata>=4.6 # [py37]

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help
    - gwf --version

about:
  home: https://gwf.app/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: A flexible, pragmatic workflow tool.
  doc_url: https://gwf.app/
  dev_url: https://github.com/gwforg/gwf

extra:
  recipe-maintainers:
    - dansondergaard
